#!/usr/bin/env zsh

# Less Colors for Man Pages
export LESS_TERMCAP_mb=$'\e[01;31m'       # begin blinking
export LESS_TERMCAP_md=$'\e[01;38;5;74m'  # begin bold
export LESS_TERMCAP_me=$'\e[0m'           # end mode
export LESS_TERMCAP_se=$'\e[0m'           # end standout-mode
export LESS_TERMCAP_so=$'\e[38;5;246m'    # begin standout-mode - info box
export LESS_TERMCAP_ue=$'\e[0m'           # end underline
export LESS_TERMCAP_us=$'\e[04;38;5;146m' # begin underline

export EDITOR="vim"
export MANPAGER="sh -c 'col -bx | bat -l man -p'"
export BAT_THEME="Solarized (dark)"

# configure history
export HISTFILE="/Users/${USER}/.zsh_history"
export HISTSIZE=10000
export SAVEHIST=10000
setopt SHARE_HISTORY
setopt HIST_IGNORE_DUPS
setopt EXTENDED_HISTORY

command -v bat > /dev/null && alias cat='bat --pager=never'
command -v bat > /dev/null && alias less='bat'
alias ls='ls -la --color=auto --group-directories-first'
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'
alias dc='docker-compose'
alias hm='helm'
alias gco='git checkout'
alias gf='git diff'
alias gcm='git commit'
alias gp='git push origin HEAD'
alias gs='git status'
alias history='history 1'

# Switch between different JDK versions
# jdk() {
#   version=$1
#   JAVA_HOME=$(/usr/libexec/java_home -v"$version");
#   export JAVA_HOME
#   java -version

#   # Can change version by running
#   # `jdk 13` in the terminal
# }

# enable completion
autoload -Uz compinit; compinit -i

zmodload -i zsh/complist

autoload -U +X bashcompinit; bashcompinit

if [ $commands[kubectl] ]; then 
  source <(kubectl completion zsh)
  
  alias k="kubecolor"
  alias kubectl="kubecolor"
  alias kg='kubectl get'
  alias kd='kubectl describe'
  complete -F __start_kubectl k
  complete -o default -F __start_kubectl kubecolor
  complete -o default -F __start_kubectl k
fi

eval "$(dircolors ${HOME}/.dir_colors/dircolors.256dark)"

# jdk 13 &> /dev/null

source /usr/local/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

# Pure prompt
fpath+=${HOME}/.zsh/pure

autoload -U promptinit; promptinit

# change the path color
zstyle :prompt:pure:path color white

prompt pure

set -o emacs
