#!/usr/bin/env zsh

# Less Colors for Man Pages
export LESS_TERMCAP_mb=$'\e[01;31m'       # begin blinking
export LESS_TERMCAP_md=$'\e[01;38;5;74m'  # begin bold
export LESS_TERMCAP_me=$'\e[0m'           # end mode
export LESS_TERMCAP_se=$'\e[0m'           # end standout-mode
export LESS_TERMCAP_so=$'\e[38;5;246m'    # begin standout-mode - info box
export LESS_TERMCAP_ue=$'\e[0m'           # end underline
export LESS_TERMCAP_us=$'\e[04;38;5;146m' # begin underline

# Adding GNU core utilities to `$PATH`.
export PATH="/usr/local/opt/grep/libexec/gnubin:$PATH"
export PATH="/usr/local/opt/coreutils/libexec/gnubin:$PATH"

# export brewed packages to PATH
export PATH="/usr/local/opt/ruby/bin:$PATH"
export PATH="/usr/local/opt/openssl@1.1/bin:$PATH"
export PATH="/usr/local/opt/python@3.8/bin:$PATH"
export PATH="/usr/local/opt/ssh-copy-id/bin:$PATH"
export PATH="/usr/local/opt/curl/bin:$PATH"
export PATH="/usr/local/opt/icu4c/bin:$PATH"
export PATH="/usr/local/opt/icu4c/sbin:$PATH"
export PATH="/usr/local/opt/sqlite/bin:$PATH"
export PATH="/usr/local/opt/gnu-sed/libexec/gnubin:$PATH"
export PATH="/usr/local/lib/ruby/gems/3.*/bin:$PATH"
export PATH="/usr/local/sbin:$PATH"

# Set LDFLAGS and CPPFLAGS flags
export LDFLAGS="-L/usr/local/opt/ruby/lib -L/usr/local/opt/curl/lib -L/usr/local/opt/python@3.8/lib -L/usr/local/opt/openssl@1.1/lib -L/usr/local/opt/libffi/lib -L/usr/local/opt/icu4c/lib -L/usr/local/opt/sqlite/lib"
export CPPFLAGS="-I/usr/local/opt/ruby/include -I/usr/local/opt/openssl@1.1/include -I/usr/local/opt/curl/include -I/usr/local/opt/libffi/include -I/usr/local/opt/icu4c/include -I/usr/local/opt/sqlite/include"

export PKG_CONFIG_PATH="$PKG_CONFIG_PATH:/usr/local/opt/curl/lib/pkgconfig"
export PKG_CONFIG_PATH="$PKG_CONFIG_PATH:/usr/local/opt/ruby/lib/pkgconfig"

export EDITOR="vim"
export MANPAGER="sh -c 'col -bx | bat -l man -p'"
export BAT_THEME="Solarized (dark)"

# configure history
export HISTFILE="/Users/${USER}/.zsh_history"
export HISTSIZE=10000
export SAVEHIST=10000
setopt SHARE_HISTORY
setopt HIST_IGNORE_DUPS
setopt EXTENDED_HISTORY

command -v bat > /dev/null && alias cat='bat --pager=never'
command -v bat > /dev/null && alias less='bat'
alias ls='ls -la --color=auto --group-directories-first'
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'
alias dc='docker-compose'
alias hm='helm'
alias gco='git checkout'
alias gf='git diff'
alias gcm='git commit'
alias gp='git push origin HEAD'
alias gs='git status'
alias history='history 1'

# Switch between different JDK versions
# jdk() {
#   version=$1
#   JAVA_HOME=$(/usr/libexec/java_home -v"$version");
#   export JAVA_HOME
#   java -version

#   # Can change version by running
#   # `jdk 13` in the terminal
# }

# enable completion
autoload -Uz compinit; compinit -i

zmodload -i zsh/complist

autoload -U +X bashcompinit; bashcompinit

if [ $commands[kubectl] ]; then 
  source <(kubectl completion zsh)
  
  alias k="kubecolor"
  alias kubectl="kubecolor"
  alias kg='kubectl get'
  alias kd='kubectl describe'
  complete -F __start_kubectl k
  complete -o default -F __start_kubectl kubecolor
  complete -o default -F __start_kubectl k
fi

eval "$(dircolors ${HOME}/.dir_colors/dircolors.256dark)"

# jdk 13 &> /dev/null

source /usr/local/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

# Pure prompt
fpath+=${HOME}/.zsh/pure

autoload -U promptinit; promptinit

# change the path color
zstyle :prompt:pure:path color white

prompt pure

set -o emacs
