#!/usr/bin/env bash

set -euo pipefail

echo -e "Symlinking.. \U1F517"

# Start the symlink
ln -sf "${PWD}/functions/zsh_private" "${HOME}/.zsh_private"
ln -sf "${PWD}/.vimrc" "${HOME}/.vimrc"
ln -sf "${PWD}/.tmux.conf" "${HOME}/.tmux.conf"
ln -sf "${PWD}/.gitconfig" "${HOME}/.gitconfig"

if [[ $(uname -m) == 'arm64' ]]; then
    "${HOMEBREW_PREFIX}/bin/code" && sleep 5
else
    /usr/local/bin/code && sleep 5
fi

if [ ! -f "${HOME}"/Library/Application\ Support/Code/User/settings.json ]; then
    touch "${HOME}"/Library/Application\ Support/Code/User/settings.json
fi

if [ ! -f "${HOME}"/Library/Application\ Support/Code/User/keybindings.json ]; then
    touch "${HOME}"/Library/Application\ Support/Code/User/keybindings.json
fi

ln -sf "${PWD}/vscode/settings.json" "${HOME}"/Library/Application\ Support/Code/User/settings.json
ln -sf "${PWD}/vscode/keybindings.json" "${HOME}"/Library/Application\ Support/Code/User/keybindings.json

if [ ! -f "${HOME}/.zshrc" ]; then
    touch "${HOME}/.zshrc"
fi

if grep -Fxq "[ -r ${HOME}/.zsh_private ] && source ${HOME}/.zsh_private" "${HOME}/.zshrc"; then
    echo ''
else
    echo "[ -r ${HOME}/.zsh_private ] && source ${HOME}/.zsh_private" >> "${HOME}/.zshrc"
fi
